---
- name: Ensure /etc/letsencrypt exists
  file:
    state: directory
    path: /etc/letsencrypt
    owner: root
    group: root
    mode: 0700
  when: inventory_hostname in groups['webservers'] or
        inventory_hostname in groups['insight']   or
        inventory_hostname in groups['panel']

- name: Install Certificates
  copy:
    dest: "/etc/letsencrypt/live"
    src: "{{ role_path }}/files/letsencrypt/live/"
    directory_mode: 0700
    mode: 0600
    owner: root
    group: root
  when: inventory_hostname in groups['webservers'] or
        inventory_hostname in groups['insight']   or
        inventory_hostname in groups['panel']

