---
- name: Install /etc/lighttpd/conf.d/{{ site.domain }}
  template:
    src: "{{ role_path }}/templates/lighttpd-conf-domain.j2"
    dest: "/etc/lighttpd/conf.d/{{ site.domain }}"
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes # Custom config with chattr +i, don't fail on error.

- name: Remove any prexisting /var/www/{{ site.domain }}.
  file:
    path: "/var/www/{{ site.domain }}"
    state: absent

- name: Ensure /var/www/{{ site.domain }} is populated.
  copy:
    src: "{{ site.www_dir }}"
    dest: "/var/www/{{ site.domain }}"
    mode: '0644'
    directory_mode: '0755'
    owner: 'www-data'
    group: 'www-data'

- name: Install /var/www/{{ site.domain }}/config.yml
  template:
    src: "{{ role_path }}/templates/markdownsite-config.yml.j2"
    dest: "/var/www/{{ site.domain }}/config.yml"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Reload lighttpd to begin serving the website.
  systemd:
    name: lighttpd
    state: reloaded

