---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install packages
  apt:
    name: [
      'git',
      'build-essential',
      'adduser',
      'libfontconfig',
      'git',
      'nginx',
      'python3-cairo',
      'python3-cairocffi',
      'python3-django',
      'python3-pyparsing',
      'python3-memcache',
      'python3-ldap',
      'python3-whitenoise',
      'python3-django-tagging',
      'python3-twisted',
      'uwsgi-plugin-python3',
      'uwsgi',
    ]
    state: present

- name: Generate /etc/nginx/ssl-dhparams.pem
  shell: openssl dhparam -out /etc/nginx/ssl-dhparams.pem 4096
  args:
    creates: /etc/nginx/ssl-dhparams.pem

- name: Create graphite user
  user:
    name: graphite
    shell: /bin/bash
    comment: User for graphite/carbon/whipser.

- include_tasks: graphite-web.yml

- include_tasks: carbon-whisper.yml

- include_tasks: grafana.yml

- include_tasks: collectd.yml

- name: Restart uwsgi (graphite-web)
  service:
    name: uwsgi
    enabled: true
    state: restarted

# To create a user for onself, use the following command:
#
# PYTHONPATH=/opt/graphite/webapp django-admin createsuperuser --settings=graphite.settings
# 
# You will be prompted to enter a username/email/password combination that can be used for login.
